In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Q1) Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

arr = np.arange(0,5)
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
# Q2) Given a Numpy 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])

print(arr.dtype == np.float64)

True


In [ ]:
# Q3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+1j, 2+2j, 3+3j])
print(arr)

[1.+1.j 2.+2.j 3.+3.j]


In [ ]:
# Q4) Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 2. 3. 4. 5.]


In [ ]:
# Q5) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.11, 2.22, 3.33, 4.44])
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.11 2.22 3.33 4.44]


In [ ]:
# Q6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(array):
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data Type: {array.dtype}")

In [ ]:
array_attributes(arr)

Shape: (4,)
Size: 4
Data Type: float64


In [ ]:
# Q7) Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(array):
    print(f"Dimensionality: {array.ndim}")

In [ ]:
array_dimension(arr)

Dimensionality: 1


In [ ]:
# Q8) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(array):
    print(f"Item Size: {array.itemsize}")
    print(f"Total Size: {array.nbytes}")

In [ ]:
item_size_info(arr)

Item Size: 8
Total Size: 32


In [ ]:
# Q9) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(array):
    print(f"Strides: {array.strides}")

In [ ]:
array_strides(arr)

Strides: (8,)


In [ ]:
# Q10) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(array):
    print(f"Shape: {array.shape}")
    print(f"Strides: {array.strides}")

In [ ]:
shape_stride_relationship(arr)

Shape: (4,)
Strides: (8,)


In [ ]:
# Q11) Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

In [ ]:
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Q12) Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [ ]:
create_ones_matrix(3, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
''' Q13)  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`. '''

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [ ]:
generate_range_array(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
''' Q14) Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).'''

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [ ]:
generate_linear_space(0, 10, 2)

array([ 0., 10.])

In [ ]:
# Q15)  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

In [ ]:
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Q16) Write a function that takes a Python list and converts it into a NumPy array.

list1 = [1, 2, 3, 4, 5]
def create_array_from_list(list):
    return np.array(list)

In [ ]:
create_array_from_list(list1)

array([1, 2, 3, 4, 5])

In [ ]:
# Q17) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
print(arr_view)

[1 2 3 4 5]


In [ ]:
# Q18) Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenates_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

In [ ]:
# Q19)  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)

[1 2 3 4 5 6]


In [ ]:
# Q20) Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):
    return np.vstack(arrays)

In [ ]:
# Q21) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_array_of_integers(start, stop, step):
    return np.arange(start, stop+1, step)

In [ ]:
# Q22) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def create_array_of_equally_spaced_values():
    return np.linspace(0, 1, 10)

In [ ]:
create_array_of_equally_spaced_values()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [62]:
# Q23) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def create_array_of_logarithmically_spaced_values():
    return np.logspace(1, 1000, 5)

In [63]:
create_array_of_logarithmically_spaced_values()

/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [70]:
# Q24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

df = pd.DataFrame(np.random.randint(1, 100, (5, 3)))
df

0   1   2
0  13   1  20
1  32  37  60
2  11  56  95
3  84  70  43
4  14  34  72

In [73]:
# Q25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negative_values(df, column_name):
    df.loc[df[column_name] < 0, column_name] = 0

In [75]:
# Q26) Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [77]:
# Q27)  Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


In [79]:
# Q28) Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])

greater = arr[arr > 5]
print(greater)

[ 8 10  7]


In [81]:
# Q29) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

slice_arr = arr[2:6]
print(slice_arr)


[3 4 5 6]


In [86]:
# Q30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [88]:
# Q31) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements(arr, indices):
    return arr[indices]

In [93]:
# Q32)  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

arr = np.array([1, 2, 3, 4, 5, 1, 6, 7, 8, 9])

def filter_elements(arr):
    return arr[arr > min(arr)]

In [94]:
filter_elements(arr)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# Q33) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elements(arr, x, y, z):
    return arr[x, y, z]

In [97]:
# Q34) Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def extract_elements(arr, condition1, condition2):
    return arr[(arr > condition1) & (arr < condition2)]

In [99]:
# Q35) Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

In [100]:
# Q36) Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [105]:
# Q37)  Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

arr1 @ arr2

array([[38, 44, 50, 56]])

In [108]:
# 38) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])

arr2 + arr1.T

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [109]:
# 39) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[1, 2, 3]])

arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [113]:
# 40) Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[1, 2],[3, 4]])



In [116]:
# Q41) Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [117]:
# Q42) Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)


array([3, 6])

In [118]:
# Q43) For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.argmax(axis=0)

array([1, 1, 1])

In [119]:
# Q44) For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [120]:
# Q45) In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr % 2 == 0, axis=0)

array([False, False, False])

In [123]:
# Q46) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape(2, 3)
reshaped_matrix = np.asmatrix(reshaped_array)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [125]:
# Q47) Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
    return matrix.flatten()

In [126]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [127]:
# Q48) Write a function that concatenates two given arrays along a specified axis.

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

In [130]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenate_arrays(array1, array2, axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
concatenates_arrays(array1, array2, axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [132]:
# Q49) Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(array, indices, axis):
    return np.split(array, indices, axis)

In [134]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_array(original_array, [1, 2], axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [135]:
# Q50) Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    array = np.insert(array, indices_to_insert, values_to_insert)
    array = np.delete(array, indices_to_delete)
    return array


In [136]:
# Q51) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2'

arr1 = np.random.randint(1, 100, 10)
arr2 = np.arange(1, 11)

arr1 + arr2

array([93, 80, 36, 19, 87, 94, 11, 58, 31, 99])

In [142]:
# Q52) Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10,1,-1)
arr2 = np.arange(1,10)

arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7])

In [144]:
# Q53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 100, 5)
arr2 = np.arange(1, 6)

arr1 * arr2

array([ 66, 140,  93,   8, 235])

In [4]:
# Q54) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

arr1 / arr2

array([2., 2., 2., 2., 2.])

In [7]:
# Q55) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = np.flip(arr1)

arr1 ** arr2

array([ 1, 16, 27, 16,  5])

In [10]:
# Q56) Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring):
    count = 0
    for string in arr:
        if substring in string:
            count += 1
    return count

In [11]:
count_substring(arr, 'hello')

3

In [12]:
# Q57) Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    uppercase_chars = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_chars.append(char)
    return uppercase_chars

In [13]:
extract_uppercase(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [14]:
# Q58) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


In [20]:
# Q59)  Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)


In [21]:
concatenate_strings(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [24]:
# Q60) Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_element(arr):
    for element in arr:
        longest = ''
        if len(element) > len(longest):
           longest = element
    return longest


In [25]:
longest_element(arr)

'pineapple'

In [32]:
# Q61) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

arr = np.random.randint(1, 1001, 100)
print(arr.mean())
print(np.median(arr))
print(arr.var())
print(arr.std())

482.38
475.0
80468.85560000001
283.6703290793734


In [33]:
# Q62) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

np.random.seed(0)
arr = np.random.randint(1, 101, 50)
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

32.25
77.25


In [34]:
# Q63) Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

arr1 = np.random.randint(1, 10, 5)
arr2 = np.random.randint(1, 10, 5)

np.corrcoef(arr1, arr2)

array([[ 1.        , -0.49507115],
       [-0.49507115,  1.        ]])

In [37]:
# Q64) Create two matrices and perform matrix multiplication using NumPy's `dot` function.

arr1 = np.random.randint(1, 10, (2, 3))
arr2 = np.random.randint(1, 10, (3, 2))

np.dot(arr1, arr2)

array([[69, 41],
       [92, 54]])

In [42]:
# Q65) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

arr = np.random.randint(10, 1001, 50)

print(np.percentile(arr, 10))
print(np.percentile(arr, 50))
print(np.percentile(arr, 90))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

116.60000000000002
516.5
781.8
223.0
717.0


In [53]:
# Q66)  Create a NumPy array of integers and find the index of a specific element.

np.random.seed(0)
arr = np.random.randint(1, 101, 10)

print(arr)
print("Index at: ", np.where(arr==65))

[45 48 65 68 68 10 84 22 37 88]
Index at:  (array([2]),)


In [56]:
# Q67)  Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1, 101, 100)

np.sort(arr)

array([  1,   1,   3,   3,   3,   4,   4,   5,  11,  11,  12,  12,  14,
        14,  15,  15,  17,  19,  20,  20,  21,  22,  22,  24,  25,  25,
        25,  26,  27,  28,  30,  31,  32,  33,  33,  34,  35,  36,  37,
        37,  39,  41,  41,  42,  42,  43,  43,  44,  44,  47,  47,  49,
        51,  52,  53,  55,  55,  57,  57,  57,  59,  59,  60,  61,  61,
        62,  62,  63,  66,  67,  68,  68,  68,  71,  72,  73,  73,  74,
        76,  78,  78,  78,  80,  81,  81,  82,  83,  84,  86,  87,  87,
        94,  95,  95,  96,  97,  99,  99,  99, 100])

In [57]:
# Q68)  Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

arr[arr > 20]

array([25, 42, 30])

In [58]:
# Q69) Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])
arr[arr%3 == 0 ]

array([12, 15])

In [61]:
# Q70)  Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
arr[(arr >= 20) & (arr <= 40)]

array([20, 30, 40])

In [62]:
# Q71) For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [3]:
# Q72) For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

array([16777216, 33554432, 50331648], dtype=int32)

In [4]:
# Q73) For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [7]:
# Q74) For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.newbyteorder().byteswap()

print(swapped_arr)

[1 2 3]


In [8]:
# Q75) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.newbyteorder().byteswap()

In [9]:
# Q76) Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print(arr1)
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


In [28]:
# Q77) Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

np.random.seed(0)
arr = np.random.randint(1, 101, (3, 3))
matrix = np.asmatrix(arr)
view_slice = matrix[1:3, 1:3]

print("Original Matrix : \n", matrix)
print("Slice of Matrix : \n" , view_slice)

view_slice[0, 0]= 100

print("Modified Slice : \n", view_slice)
print("Original Matrix : \n", matrix)

Original Matrix : 
 [[45 48 65]
 [68 68 10]
 [84 22 37]]
Slice of Matrix : 
 [[68 10]
 [22 37]]
Modified Slice : 
 [[100  10]
 [ 22  37]]
Original Matrix : 
 [[ 45  48  65]
 [ 68 100  10]
 [ 84  22  37]]


In [38]:
# Q78) Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, 1:3]
view_b = view_b + 5
print(view_b)
print(array_a)

[[10 11]
 [13 14]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
# Q79) Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
print("Original Array : \n", orig_array)
print("Reshaped Array: \n", reshaped_view)

reshaped_view[0, 0] = 100
print("Original Array : \n", orig_array)
print("Reshaped Array: \n", reshaped_view)

Original Array : 
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Original Array : 
 [[100   2   3   4]
 [  5   6   7   8]]
Reshaped Array: 
 [[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [50]:
# Q80)   Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data =  np.random.randint(1, 13, (3, 4))
data_copy = data[data > 5]
data_copy[0] = 100
print(data)
print(data_copy)



[[ 7  8 12  3]
 [12  1  4  6]
 [10 11  5 12]]
[100   8  12  12   6  10  11  12]


In [51]:
# Q81)  Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 10, (2, 2))
A = np.asmatrix(A)
B = np.random.randint(1, 10, (2, 2))
B = np.asmatrix(B)

print(A + B)
print(A - B)

[[ 9 12]
 [10 14]]
[[ 1  2]
 [ 0 -4]]


In [53]:
# Q82) Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.asmatrix(np.random.randint(1, 10, (3, 2)))
D = np.asmatrix(np.random.randint(1, 10, (2, 4)))

print(C @ D)


[[10 30 28 12]
 [ 9 16 23 13]
 [13 22 33 19]]


In [56]:
# Q83) Create a matrix `E` and find its transpose.

E = np.asmatrix(np.random.randint(1, 10, (4, 2)))
print("Original Matrix : \n" , E)
print("Transpose Matrix : \n", E.T)

Original Matrix : 
 [[4 3]
 [4 5]
 [2 3]
 [2 5]]
Transpose Matrix : 
 [[4 4 2 2]
 [3 5 3 5]]


In [59]:
# Q84) Generate a square matrix `F` and compute its determinant.

F = np.asmatrix(np.random.randint(1, 10, (3, 3)))
print(np.linalg.det(F))

-27.0


In [60]:
# Q85) Create a square matrix `G` and find its inverse.

G = np.asmatrix(np.random.randint(1, 10, (3, 3)))
print(np.linalg.inv(G))

[[-0.04895105 -0.02097902  0.12587413]
 [-0.02564103  0.17948718 -0.07692308]
 [ 0.14219114 -0.17715618  0.06293706]]
